name: Build image

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build, push and test the image
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    env:
      image_name: ghcr.io/${{ github.repository_owner }}/nim-ci

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate metadata for the test image
        id: docker_test_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: |
            localhost:5000/test/nim-ci
          tag-edge: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host

      - name: Login to Github registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push
        id: build
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/386,linux/arm64,linux/arm/v7
          push: true
          tags: ${{ steps.docker_test_meta.outputs.tags }}
          labels: ${{ steps.docker_test_meta.outputs.labels }}

      - name: Run tests
        run: |
          set -eu
          curl -LO https://storage.googleapis.com/container-structure-test/latest/container-structure-test-linux-amd64
          chmod +x container-structure-test-linux-amd64
          image=localhost:5000/test/nim-ci@${{ steps.build.outputs.digest }}
          echo "testing $image"
          ./container-structure-test-linux-amd64 test \
            --image "$image" --pull \
            --config test.yml

      - name: Generate metadata for the release image
        if: github.event_name != 'pull_request'
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: |
            ${{ env.image_name }}
          tag-edge: true
          tag-sha: true

      - name: Tag and push
        if: github.event_name != 'pull_request'
        run: |
          set -eu
          image=localhost:5000/test/nim-ci@${{ steps.build.outputs.digest }}
          for tag in '${{ steps.docker_meta.outputs.tags }}'; do
            docker image tag "$image" "$tag"
          done

          docker push --all-tags "$image_name"
